#!/bin/sh

while true; do
  ruby parser.rb
  
  for file in iptv-sports.xml iptv-sports.m3u; do
    aws s3 cp "$file" "s3://maddox/channels/iptv/$file"
    aws s3api put-object-acl --bucket "maddox" --key "channels/iptv/$file" --acl public-read
  done

  echo "Waiting 60 minutes..."
  sleep 3600
done
