// Command zones writes internal/store/zones.go, the list of time zones the UI offers.
//
// Two sources, because neither answers on its own. tzdata's zone.tab and zone1970.tab name
// the zones a person would pick — one per country or region, with none of the
// backward-compatibility spellings that make a picker look broken (Africa/Asmera beside
// Africa/Asmara, Asia/Calcutta beside Asia/Kolkata, US/Eastern beside America/New_York).
// The Go toolchain's own zoneinfo.zip says which names time.LoadLocation will actually
// accept. A zone has to be in both.
//
// Run it with `make zones` after a Go upgrade brings newer tzdata.
package main

import (
	"archive/zip"
	"bufio"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

// tables are tzdata's own indexes of pickable zones. zone1970.tab drops zones whose
// country has since been merged into a neighbour's rules, so zone.tab is read as well:
// someone in Oslo should find Europe/Oslo rather than be told to know it is Berlin now.
var tables = []string{
	"/usr/share/zoneinfo/zone.tab",
	"/usr/share/zoneinfo/zone1970.tab",
}

func main() {
	loadable, err := goZones()
	if err != nil {
		fail(err)
	}
	named := map[string]bool{}
	for _, t := range tables {
		if err := readTable(t, named); err != nil {
			fail(err)
		}
	}
	if len(named) == 0 {
		fail(fmt.Errorf("no zones read from %s; is tzdata installed?", strings.Join(tables, " or ")))
	}

	var zones []string
	for name := range named {
		if loadable[name] {
			zones = append(zones, name)
		}
	}
	sort.Strings(zones)
	// UTC belongs to no country, so no table lists it, and every install understands it.
	zones = append([]string{"UTC"}, zones...)

	var b strings.Builder
	b.WriteString("// Code generated by scripts/zones. DO NOT EDIT.\n\npackage store\n\n")
	b.WriteString("// Zones is every time zone the UI offers: the ones tzdata lists as a place a person\n")
	b.WriteString("// would choose, kept to those the Go runtime can load, so anything picked here is a\n")
	b.WriteString("// name time.LoadLocation accepts.\n")
	b.WriteString("var Zones = []string{\n")
	for _, z := range zones {
		fmt.Fprintf(&b, "\t%q,\n", z)
	}
	b.WriteString("}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile("internal/store/zones.go", src, 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("wrote internal/store/zones.go with %d zones\n", len(zones))
}

// goZones is every name the Go runtime's own database holds.
func goZones() (map[string]bool, error) {
	path := filepath.Join(runtime.GOROOT(), "lib", "time", "zoneinfo.zip")
	r, err := zip.OpenReader(path)
	if err != nil {
		return nil, err
	}
	defer r.Close()
	out := map[string]bool{}
	for _, f := range r.File {
		if !strings.HasSuffix(f.Name, "/") {
			out[f.Name] = true
		}
	}
	return out, nil
}

// readTable collects the zone name from each row of a tzdata table: country codes,
// coordinates, then the name.
func readTable(path string, into map[string]bool) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if strings.HasPrefix(line, "#") || strings.TrimSpace(line) == "" {
			continue
		}
		if cols := strings.Split(line, "\t"); len(cols) >= 3 {
			into[strings.TrimSpace(cols[2])] = true
		}
	}
	return sc.Err()
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "zones:", err)
	os.Exit(1)
}
